# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=225)),
                ('priority', models.CharField(choices=[('3', 'High'), ('1', 'low'), ('2', 'Medium')], default='2', max_length=1)),
                ('state_task', models.CharField(choices=[('todo', 'Todo'), ('doing', 'Doing'), ('done', 'Done')], default='todo', max_length=10)),
                ('due_date', models.DateField()),
            ],
        ),
    ]
